name: go build and Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update apt packages
        run: |
          sudo apt update
          sudo apt upgrade -y

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: make all-arch -j

      - name: Create tar
        run: |
          tar -cf okapi-utils_linux_amd64.tar build/linux/amd64/*
          tar -cf okapi-utils_linux_arm64.tar build/linux/arm64/*
          tar -cf okapi-utils_linux_386.tar build/linux/386/*
          tar -cf okapi-utils_windows_amd64.tar build/windows/amd64/*
          tar -cf okapi-utils_windows_arm64.tar build/windows/arm64/*
          tar -cf okapi-utils_windows_386.tar build/windows/386/*
          tar -cf okapi-utils.tar build/*
          zstd -T0 --ultra -22 okapi-utils*.tar

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            okapi-utils_linux_amd64.tar
            okapi-utils_linux_arm64.tar
            okapi-utils_linux_386.tar
            okapi-utils_windows_amd64.tar
            okapi-utils_windows_arm64.tar
            okapi-utils_windows_386.tar
            okapi-utils_linux_amd64.tar.zst
            okapi-utils_linux_arm64.tar.zst
            okapi-utils_linux_386.tar.zst
            okapi-utils_windows_amd64.tar.zst
            okapi-utils_windows_arm64.tar.zst
            okapi-utils_windows_386.tar.zst
            okapi-utils.tar
            okapi-utils.tar.zst
            
  upload:
    name: Upload release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Delete old release and tag
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          continue_on_error: true
          delete_release: true
          tag_name: latest_auto
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get artifacts
        uses: actions/download-artifact@v3

      - name: List dr
        run: ls -lha

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
            name: Latest Autobuild
            tag: latest_auto
            commit: main
            body: ${{ github.event.head_commit.message }}
            artifacts: |
                build/okapi-utils_linux_amd64.tar
                build/okapi-utils_linux_arm64.tar
                build/okapi-utils_linux_386.tar
                build/okapi-utils_windows_amd64.tar
                build/okapi-utils_windows_arm64.tar
                build/okapi-utils_windows_386.tar
                build/okapi-utils_linux_amd64.tar.zst
                build/okapi-utils_linux_arm64.tar.zst
                build/okapi-utils_linux_386.tar.zst
                build/okapi-utils_windows_amd64.tar.zst
                build/okapi-utils_windows_arm64.tar.zst
                build/okapi-utils_windows_386.tar.zst
                build/okapi-utils.tar
                build/okapi-utils.tar.zst
            prerelease: true